### ISSUE TITLE
The sandbox is not available in beforeEach hooks when using the new hooks API.

### ISSUE THREAD

**Issue by lbdm44** [scalvert/ember-sinon-sandbox#46]
When writing a test using the new qunit hooks api, `this.sandbox` is not available in the customized `beforeEach` hooks.

The below example will throw an error when the custom `beforeEach` is ran indicating that `this.sandbox` is `undefined`.

```js
import { module, test } from 'qunit';
import { setupSinonSandbox } from 'ember-sinon-sandbox/test-support';

const myThing = {
  fooBar(one, two) {
    return one === two;
  },

  barBaz(one, two) {
    return !fooBar(one, two);
  }
};

module('my module', function(hooks) {
  setupSinonSandbox(hooks);

  hooks.beforeEach(() => {
    this.sandbox.stub(myThing, 'fooBar').returns(false);
  });

  test('my test', function(assert) {
    assert.ok(myThing.barBaz(1, 2));
  })
})
```

**Comment by scalvert** [comment]
You're using arrow functions in your `beforeEach`. You need to use `function`.

**Comment by scalvert** [comment]
Tests: 

https://github.com/scalvert/ember-sinon-sandbox/blob/master/tests/unit/setup-sinon-sandbox-test.js#L36
https://github.com/scalvert/ember-sinon-sandbox/blob/master/tests/unit/setup-sinon-sandbox-ember-qunit-test.js
